// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group_base.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "group_base.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace zproto {

namespace {

const ::google::protobuf::Descriptor* Member_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Member_reflection_ = NULL;
const ::google::protobuf::Descriptor* Group_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Group_reflection_ = NULL;
const ::google::protobuf::Descriptor* Group_ExtEntry_descriptor_ = NULL;
const ::google::protobuf::Descriptor* GroupFull_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GroupFull_reflection_ = NULL;
const ::google::protobuf::Descriptor* GroupFull_ExtEntry_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* GroupType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* GroupPermissions_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* GroupFullPermissions_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_group_5fbase_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_group_5fbase_2eproto() {
  protobuf_AddDesc_group_5fbase_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "group_base.proto");
  GOOGLE_CHECK(file != NULL);
  Member_descriptor_ = file->message_type(0);
  static const int Member_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, inviter_uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, is_admin_),
  };
  Member_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Member_descriptor_,
      Member::default_instance_,
      Member_offsets_,
      -1,
      -1,
      -1,
      sizeof(Member),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Member, _is_default_instance_));
  Group_descriptor_ = file->message_type(1);
  static const int Group_offsets_[17] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, access_hash_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, title_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, avatar_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, members_count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, is_member_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, is_hidden_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, group_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, permissions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, is_deleted_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, ext_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, is_admin_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, creator_uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, members_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, create_date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, theme_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, about_),
  };
  Group_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Group_descriptor_,
      Group::default_instance_,
      Group_offsets_,
      -1,
      -1,
      -1,
      sizeof(Group),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Group, _is_default_instance_));
  Group_ExtEntry_descriptor_ = Group_descriptor_->nested_type(0);
  GroupFull_descriptor_ = file->message_type(2);
  static const int GroupFull_offsets_[11] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, create_date_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, owner_uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, members_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, theme_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, about_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, ext_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, is_async_members_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, is_shared_history_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, short_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, permissions_),
  };
  GroupFull_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GroupFull_descriptor_,
      GroupFull::default_instance_,
      GroupFull_offsets_,
      -1,
      -1,
      -1,
      sizeof(GroupFull),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GroupFull, _is_default_instance_));
  GroupFull_ExtEntry_descriptor_ = GroupFull_descriptor_->nested_type(0);
  GroupType_descriptor_ = file->enum_type(0);
  GroupPermissions_descriptor_ = file->enum_type(1);
  GroupFullPermissions_descriptor_ = file->enum_type(2);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_group_5fbase_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Member_descriptor_, &Member::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Group_descriptor_, &Group::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
        Group_ExtEntry_descriptor_,
        ::google::protobuf::internal::MapEntry<
            ::std::string,
            ::zproto::RawArrayValue,
            ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
            ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
            0>::CreateDefaultInstance(
                Group_ExtEntry_descriptor_));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GroupFull_descriptor_, &GroupFull::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
        GroupFull_ExtEntry_descriptor_,
        ::google::protobuf::internal::MapEntry<
            ::std::string,
            ::zproto::RawArrayValue,
            ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
            ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
            0>::CreateDefaultInstance(
                GroupFull_ExtEntry_descriptor_));
}

}  // namespace

void protobuf_ShutdownFile_group_5fbase_2eproto() {
  delete Member::default_instance_;
  delete Member_reflection_;
  delete Group::default_instance_;
  delete Group_reflection_;
  delete GroupFull::default_instance_;
  delete GroupFull_reflection_;
}

void protobuf_AddDesc_group_5fbase_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_group_5fbase_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::zproto::protobuf_AddDesc_types_2eproto();
  ::zproto::protobuf_AddDesc_files_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020group_base.proto\022\006zproto\032\013types.proto\032"
    "\013files.proto\"J\n\006Member\022\013\n\003uid\030\001 \001(\t\022\023\n\013i"
    "nviter_uid\030\002 \001(\t\022\014\n\004date\030\003 \001(\003\022\020\n\010is_adm"
    "in\030\004 \001(\010\"\307\003\n\005Group\022\n\n\002id\030\001 \001(\t\022\023\n\013access"
    "_hash\030\002 \001(\003\022\r\n\005title\030\003 \001(\t\022\036\n\006avatar\030\004 \001"
    "(\0132\016.zproto.Avatar\022\025\n\rmembers_count\030\030 \001("
    "\005\022\021\n\tis_member\030\006 \001(\010\022\021\n\tis_hidden\030\024 \001(\010\022"
    "%\n\ngroup_type\030\031 \001(\0162\021.zproto.GroupType\022\023"
    "\n\013permissions\030\032 \001(\003\022\022\n\nis_deleted\030\033 \001(\010\022"
    "#\n\003ext\030\026 \003(\0132\026.zproto.Group.ExtEntry\022\020\n\010"
    "is_admin\030\020 \001(\010\022\023\n\013creator_uid\030\010 \001(\t\022\037\n\007m"
    "embers\030\t \003(\0132\016.zproto.Member\022\023\n\013create_d"
    "ate\030\n \001(\003\022\r\n\005theme\030\021 \001(\t\022\r\n\005about\030\022 \001(\t\032"
    "A\n\010ExtEntry\022\013\n\003key\030\001 \001(\t\022$\n\005value\030\002 \001(\0132"
    "\025.zproto.RawArrayValue:\0028\001\"\310\002\n\tGroupFull"
    "\022\n\n\002id\030\001 \001(\t\022\023\n\013create_date\030\002 \001(\003\022\021\n\town"
    "er_uid\030\003 \001(\t\022\037\n\007members\030\004 \003(\0132\016.zproto.M"
    "ember\022\r\n\005theme\030\005 \001(\t\022\r\n\005about\030\006 \001(\t\022\'\n\003e"
    "xt\030\007 \003(\0132\032.zproto.GroupFull.ExtEntry\022\030\n\020"
    "is_async_members\030\010 \001(\010\022\031\n\021is_shared_hist"
    "ory\030\t \001(\010\022\022\n\nshort_name\030\n \001(\t\022\023\n\013permiss"
    "ions\030\013 \001(\003\032A\n\010ExtEntry\022\013\n\003key\030\001 \001(\t\022$\n\005v"
    "alue\030\002 \001(\0132\025.zproto.RawArrayValue:\0028\001*#\n"
    "\tGroupType\022\t\n\005GROUP\020\000\022\013\n\007CHANNEL\020\001*_\n\020Gr"
    "oupPermissions\022\020\n\014SEND_MESSAGE\020\000\022\t\n\005CLEA"
    "R\020\001\022\t\n\005LEAVE\020\002\022\n\n\006DELETE\020\003\022\010\n\004JOIN\020\004\022\r\n\t"
    "VIEW_INFO\020\005*\356\001\n\024GroupFullPermissions\022\r\n\t"
    "EDIT_INFO\020\000\022\020\n\014VIEW_MEMBERS\020\001\022\022\n\016INVITE_"
    "MEMBERS\020\002\022\023\n\017INVITE_VIA_LINK\020\003\022\010\n\004CALL\020\004"
    "\022\027\n\023EDIT_ADMIN_SETTINGS\020\005\022\017\n\013VIEW_ADMINS"
    "\020\006\022\017\n\013EDIT_ADMINS\020\007\022\020\n\014KICK_INVITED\020\010\022\017\n"
    "\013KICK_ANYONE\020\t\022\020\n\014EDIT_FOREIGN\020\n\022\022\n\016DELE"
    "TE_FOREIGN\020\013B)\n\027com.zchat.engine.zprotoB"
    "\014ZProtoGroupsH\002b\006proto3", 1343);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "group_base.proto", &protobuf_RegisterTypes);
  Member::default_instance_ = new Member();
  Group::default_instance_ = new Group();
  GroupFull::default_instance_ = new GroupFull();
  Member::default_instance_->InitAsDefaultInstance();
  Group::default_instance_->InitAsDefaultInstance();
  GroupFull::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_group_5fbase_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_group_5fbase_2eproto {
  StaticDescriptorInitializer_group_5fbase_2eproto() {
    protobuf_AddDesc_group_5fbase_2eproto();
  }
} static_descriptor_initializer_group_5fbase_2eproto_;
const ::google::protobuf::EnumDescriptor* GroupType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GroupType_descriptor_;
}
bool GroupType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* GroupPermissions_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GroupPermissions_descriptor_;
}
bool GroupPermissions_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* GroupFullPermissions_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GroupFullPermissions_descriptor_;
}
bool GroupFullPermissions_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Member::kUidFieldNumber;
const int Member::kInviterUidFieldNumber;
const int Member::kDateFieldNumber;
const int Member::kIsAdminFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Member::Member()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.Member)
}

void Member::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Member::Member(const Member& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.Member)
}

void Member::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  uid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  inviter_uid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  date_ = GOOGLE_LONGLONG(0);
  is_admin_ = false;
}

Member::~Member() {
  // @@protoc_insertion_point(destructor:zproto.Member)
  SharedDtor();
}

void Member::SharedDtor() {
  uid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  inviter_uid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Member::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Member::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Member_descriptor_;
}

const Member& Member::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_group_5fbase_2eproto();
  return *default_instance_;
}

Member* Member::default_instance_ = NULL;

Member* Member::New(::google::protobuf::Arena* arena) const {
  Member* n = new Member;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Member::Swap(Member* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Member::InternalSwap(Member* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata Member::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Member_descriptor_;
  metadata.reflection = Member_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Member

// optional string uid = 1;
void Member::clear_uid() {
  uid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Member::uid() const {
  // @@protoc_insertion_point(field_get:zproto.Member.uid)
  return uid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Member::set_uid(const ::std::string& value) {
  
  uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.Member.uid)
}
 void Member::set_uid(const char* value) {
  
  uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.Member.uid)
}
 void Member::set_uid(const char* value, size_t size) {
  
  uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.Member.uid)
}
 ::std::string* Member::mutable_uid() {
  
  // @@protoc_insertion_point(field_mutable:zproto.Member.uid)
  return uid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Member::release_uid() {
  // @@protoc_insertion_point(field_release:zproto.Member.uid)
  
  return uid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Member::set_allocated_uid(::std::string* uid) {
  if (uid != NULL) {
    
  } else {
    
  }
  uid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uid);
  // @@protoc_insertion_point(field_set_allocated:zproto.Member.uid)
}

// optional string inviter_uid = 2;
void Member::clear_inviter_uid() {
  inviter_uid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Member::inviter_uid() const {
  // @@protoc_insertion_point(field_get:zproto.Member.inviter_uid)
  return inviter_uid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Member::set_inviter_uid(const ::std::string& value) {
  
  inviter_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.Member.inviter_uid)
}
 void Member::set_inviter_uid(const char* value) {
  
  inviter_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.Member.inviter_uid)
}
 void Member::set_inviter_uid(const char* value, size_t size) {
  
  inviter_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.Member.inviter_uid)
}
 ::std::string* Member::mutable_inviter_uid() {
  
  // @@protoc_insertion_point(field_mutable:zproto.Member.inviter_uid)
  return inviter_uid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Member::release_inviter_uid() {
  // @@protoc_insertion_point(field_release:zproto.Member.inviter_uid)
  
  return inviter_uid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Member::set_allocated_inviter_uid(::std::string* inviter_uid) {
  if (inviter_uid != NULL) {
    
  } else {
    
  }
  inviter_uid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), inviter_uid);
  // @@protoc_insertion_point(field_set_allocated:zproto.Member.inviter_uid)
}

// optional int64 date = 3;
void Member::clear_date() {
  date_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Member::date() const {
  // @@protoc_insertion_point(field_get:zproto.Member.date)
  return date_;
}
 void Member::set_date(::google::protobuf::int64 value) {
  
  date_ = value;
  // @@protoc_insertion_point(field_set:zproto.Member.date)
}

// optional bool is_admin = 4;
void Member::clear_is_admin() {
  is_admin_ = false;
}
 bool Member::is_admin() const {
  // @@protoc_insertion_point(field_get:zproto.Member.is_admin)
  return is_admin_;
}
 void Member::set_is_admin(bool value) {
  
  is_admin_ = value;
  // @@protoc_insertion_point(field_set:zproto.Member.is_admin)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Group::kIdFieldNumber;
const int Group::kAccessHashFieldNumber;
const int Group::kTitleFieldNumber;
const int Group::kAvatarFieldNumber;
const int Group::kMembersCountFieldNumber;
const int Group::kIsMemberFieldNumber;
const int Group::kIsHiddenFieldNumber;
const int Group::kGroupTypeFieldNumber;
const int Group::kPermissionsFieldNumber;
const int Group::kIsDeletedFieldNumber;
const int Group::kExtFieldNumber;
const int Group::kIsAdminFieldNumber;
const int Group::kCreatorUidFieldNumber;
const int Group::kMembersFieldNumber;
const int Group::kCreateDateFieldNumber;
const int Group::kThemeFieldNumber;
const int Group::kAboutFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Group::Group()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.Group)
}

void Group::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  avatar_ = const_cast< ::zproto::Avatar*>(&::zproto::Avatar::default_instance());
}

Group::Group(const Group& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.Group)
}

void Group::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  access_hash_ = GOOGLE_LONGLONG(0);
  title_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  avatar_ = NULL;
  members_count_ = 0;
  is_member_ = false;
  is_hidden_ = false;
  group_type_ = 0;
  permissions_ = GOOGLE_LONGLONG(0);
  is_deleted_ = false;
  ext_.SetAssignDescriptorCallback(
      protobuf_AssignDescriptorsOnce);
  ext_.SetEntryDescriptor(
      &::zproto::Group_ExtEntry_descriptor_);
  is_admin_ = false;
  creator_uid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  create_date_ = GOOGLE_LONGLONG(0);
  theme_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  about_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Group::~Group() {
  // @@protoc_insertion_point(destructor:zproto.Group)
  SharedDtor();
}

void Group::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  title_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  creator_uid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  theme_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  about_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete avatar_;
  }
}

void Group::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Group::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Group_descriptor_;
}

const Group& Group::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_group_5fbase_2eproto();
  return *default_instance_;
}

Group* Group::default_instance_ = NULL;

Group* Group::New(::google::protobuf::Arena* arena) const {
  Group* n = new Group;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Group::Swap(Group* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Group::InternalSwap(Group* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata Group::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Group_descriptor_;
  metadata.reflection = Group_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Group

// optional string id = 1;
void Group::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Group::id() const {
  // @@protoc_insertion_point(field_get:zproto.Group.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.Group.id)
}
 void Group::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.Group.id)
}
 void Group::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.Group.id)
}
 ::std::string* Group::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:zproto.Group.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Group::release_id() {
  // @@protoc_insertion_point(field_release:zproto.Group.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:zproto.Group.id)
}

// optional int64 access_hash = 2;
void Group::clear_access_hash() {
  access_hash_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Group::access_hash() const {
  // @@protoc_insertion_point(field_get:zproto.Group.access_hash)
  return access_hash_;
}
 void Group::set_access_hash(::google::protobuf::int64 value) {
  
  access_hash_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.access_hash)
}

// optional string title = 3;
void Group::clear_title() {
  title_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Group::title() const {
  // @@protoc_insertion_point(field_get:zproto.Group.title)
  return title_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_title(const ::std::string& value) {
  
  title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.Group.title)
}
 void Group::set_title(const char* value) {
  
  title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.Group.title)
}
 void Group::set_title(const char* value, size_t size) {
  
  title_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.Group.title)
}
 ::std::string* Group::mutable_title() {
  
  // @@protoc_insertion_point(field_mutable:zproto.Group.title)
  return title_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Group::release_title() {
  // @@protoc_insertion_point(field_release:zproto.Group.title)
  
  return title_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_allocated_title(::std::string* title) {
  if (title != NULL) {
    
  } else {
    
  }
  title_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), title);
  // @@protoc_insertion_point(field_set_allocated:zproto.Group.title)
}

// optional .zproto.Avatar avatar = 4;
bool Group::has_avatar() const {
  return !_is_default_instance_ && avatar_ != NULL;
}
void Group::clear_avatar() {
  if (GetArenaNoVirtual() == NULL && avatar_ != NULL) delete avatar_;
  avatar_ = NULL;
}
const ::zproto::Avatar& Group::avatar() const {
  // @@protoc_insertion_point(field_get:zproto.Group.avatar)
  return avatar_ != NULL ? *avatar_ : *default_instance_->avatar_;
}
::zproto::Avatar* Group::mutable_avatar() {
  
  if (avatar_ == NULL) {
    avatar_ = new ::zproto::Avatar;
  }
  // @@protoc_insertion_point(field_mutable:zproto.Group.avatar)
  return avatar_;
}
::zproto::Avatar* Group::release_avatar() {
  // @@protoc_insertion_point(field_release:zproto.Group.avatar)
  
  ::zproto::Avatar* temp = avatar_;
  avatar_ = NULL;
  return temp;
}
void Group::set_allocated_avatar(::zproto::Avatar* avatar) {
  delete avatar_;
  avatar_ = avatar;
  if (avatar) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:zproto.Group.avatar)
}

// optional int32 members_count = 24;
void Group::clear_members_count() {
  members_count_ = 0;
}
 ::google::protobuf::int32 Group::members_count() const {
  // @@protoc_insertion_point(field_get:zproto.Group.members_count)
  return members_count_;
}
 void Group::set_members_count(::google::protobuf::int32 value) {
  
  members_count_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.members_count)
}

// optional bool is_member = 6;
void Group::clear_is_member() {
  is_member_ = false;
}
 bool Group::is_member() const {
  // @@protoc_insertion_point(field_get:zproto.Group.is_member)
  return is_member_;
}
 void Group::set_is_member(bool value) {
  
  is_member_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.is_member)
}

// optional bool is_hidden = 20;
void Group::clear_is_hidden() {
  is_hidden_ = false;
}
 bool Group::is_hidden() const {
  // @@protoc_insertion_point(field_get:zproto.Group.is_hidden)
  return is_hidden_;
}
 void Group::set_is_hidden(bool value) {
  
  is_hidden_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.is_hidden)
}

// optional .zproto.GroupType group_type = 25;
void Group::clear_group_type() {
  group_type_ = 0;
}
 ::zproto::GroupType Group::group_type() const {
  // @@protoc_insertion_point(field_get:zproto.Group.group_type)
  return static_cast< ::zproto::GroupType >(group_type_);
}
 void Group::set_group_type(::zproto::GroupType value) {
  
  group_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.group_type)
}

// optional int64 permissions = 26;
void Group::clear_permissions() {
  permissions_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Group::permissions() const {
  // @@protoc_insertion_point(field_get:zproto.Group.permissions)
  return permissions_;
}
 void Group::set_permissions(::google::protobuf::int64 value) {
  
  permissions_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.permissions)
}

// optional bool is_deleted = 27;
void Group::clear_is_deleted() {
  is_deleted_ = false;
}
 bool Group::is_deleted() const {
  // @@protoc_insertion_point(field_get:zproto.Group.is_deleted)
  return is_deleted_;
}
 void Group::set_is_deleted(bool value) {
  
  is_deleted_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.is_deleted)
}

// map<string, .zproto.RawArrayValue> ext = 22;
int Group::ext_size() const {
  return ext_.size();
}
void Group::clear_ext() {
  ext_.Clear();
}
 const ::google::protobuf::Map< ::std::string, ::zproto::RawArrayValue >&
Group::ext() const {
  // @@protoc_insertion_point(field_map:zproto.Group.ext)
  return ext_.GetMap();
}
 ::google::protobuf::Map< ::std::string, ::zproto::RawArrayValue >*
Group::mutable_ext() {
  // @@protoc_insertion_point(field_mutable_map:zproto.Group.ext)
  return ext_.MutableMap();
}

// optional bool is_admin = 16;
void Group::clear_is_admin() {
  is_admin_ = false;
}
 bool Group::is_admin() const {
  // @@protoc_insertion_point(field_get:zproto.Group.is_admin)
  return is_admin_;
}
 void Group::set_is_admin(bool value) {
  
  is_admin_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.is_admin)
}

// optional string creator_uid = 8;
void Group::clear_creator_uid() {
  creator_uid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Group::creator_uid() const {
  // @@protoc_insertion_point(field_get:zproto.Group.creator_uid)
  return creator_uid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_creator_uid(const ::std::string& value) {
  
  creator_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.Group.creator_uid)
}
 void Group::set_creator_uid(const char* value) {
  
  creator_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.Group.creator_uid)
}
 void Group::set_creator_uid(const char* value, size_t size) {
  
  creator_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.Group.creator_uid)
}
 ::std::string* Group::mutable_creator_uid() {
  
  // @@protoc_insertion_point(field_mutable:zproto.Group.creator_uid)
  return creator_uid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Group::release_creator_uid() {
  // @@protoc_insertion_point(field_release:zproto.Group.creator_uid)
  
  return creator_uid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_allocated_creator_uid(::std::string* creator_uid) {
  if (creator_uid != NULL) {
    
  } else {
    
  }
  creator_uid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), creator_uid);
  // @@protoc_insertion_point(field_set_allocated:zproto.Group.creator_uid)
}

// repeated .zproto.Member members = 9;
int Group::members_size() const {
  return members_.size();
}
void Group::clear_members() {
  members_.Clear();
}
const ::zproto::Member& Group::members(int index) const {
  // @@protoc_insertion_point(field_get:zproto.Group.members)
  return members_.Get(index);
}
::zproto::Member* Group::mutable_members(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.Group.members)
  return members_.Mutable(index);
}
::zproto::Member* Group::add_members() {
  // @@protoc_insertion_point(field_add:zproto.Group.members)
  return members_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::Member >*
Group::mutable_members() {
  // @@protoc_insertion_point(field_mutable_list:zproto.Group.members)
  return &members_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::Member >&
Group::members() const {
  // @@protoc_insertion_point(field_list:zproto.Group.members)
  return members_;
}

// optional int64 create_date = 10;
void Group::clear_create_date() {
  create_date_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Group::create_date() const {
  // @@protoc_insertion_point(field_get:zproto.Group.create_date)
  return create_date_;
}
 void Group::set_create_date(::google::protobuf::int64 value) {
  
  create_date_ = value;
  // @@protoc_insertion_point(field_set:zproto.Group.create_date)
}

// optional string theme = 17;
void Group::clear_theme() {
  theme_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Group::theme() const {
  // @@protoc_insertion_point(field_get:zproto.Group.theme)
  return theme_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_theme(const ::std::string& value) {
  
  theme_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.Group.theme)
}
 void Group::set_theme(const char* value) {
  
  theme_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.Group.theme)
}
 void Group::set_theme(const char* value, size_t size) {
  
  theme_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.Group.theme)
}
 ::std::string* Group::mutable_theme() {
  
  // @@protoc_insertion_point(field_mutable:zproto.Group.theme)
  return theme_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Group::release_theme() {
  // @@protoc_insertion_point(field_release:zproto.Group.theme)
  
  return theme_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_allocated_theme(::std::string* theme) {
  if (theme != NULL) {
    
  } else {
    
  }
  theme_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), theme);
  // @@protoc_insertion_point(field_set_allocated:zproto.Group.theme)
}

// optional string about = 18;
void Group::clear_about() {
  about_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Group::about() const {
  // @@protoc_insertion_point(field_get:zproto.Group.about)
  return about_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_about(const ::std::string& value) {
  
  about_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.Group.about)
}
 void Group::set_about(const char* value) {
  
  about_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.Group.about)
}
 void Group::set_about(const char* value, size_t size) {
  
  about_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.Group.about)
}
 ::std::string* Group::mutable_about() {
  
  // @@protoc_insertion_point(field_mutable:zproto.Group.about)
  return about_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Group::release_about() {
  // @@protoc_insertion_point(field_release:zproto.Group.about)
  
  return about_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Group::set_allocated_about(::std::string* about) {
  if (about != NULL) {
    
  } else {
    
  }
  about_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), about);
  // @@protoc_insertion_point(field_set_allocated:zproto.Group.about)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GroupFull::kIdFieldNumber;
const int GroupFull::kCreateDateFieldNumber;
const int GroupFull::kOwnerUidFieldNumber;
const int GroupFull::kMembersFieldNumber;
const int GroupFull::kThemeFieldNumber;
const int GroupFull::kAboutFieldNumber;
const int GroupFull::kExtFieldNumber;
const int GroupFull::kIsAsyncMembersFieldNumber;
const int GroupFull::kIsSharedHistoryFieldNumber;
const int GroupFull::kShortNameFieldNumber;
const int GroupFull::kPermissionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GroupFull::GroupFull()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GroupFull)
}

void GroupFull::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GroupFull::GroupFull(const GroupFull& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GroupFull)
}

void GroupFull::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  create_date_ = GOOGLE_LONGLONG(0);
  owner_uid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  theme_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  about_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ext_.SetAssignDescriptorCallback(
      protobuf_AssignDescriptorsOnce);
  ext_.SetEntryDescriptor(
      &::zproto::GroupFull_ExtEntry_descriptor_);
  is_async_members_ = false;
  is_shared_history_ = false;
  short_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  permissions_ = GOOGLE_LONGLONG(0);
}

GroupFull::~GroupFull() {
  // @@protoc_insertion_point(destructor:zproto.GroupFull)
  SharedDtor();
}

void GroupFull::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  owner_uid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  theme_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  about_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  short_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void GroupFull::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GroupFull::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GroupFull_descriptor_;
}

const GroupFull& GroupFull::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_group_5fbase_2eproto();
  return *default_instance_;
}

GroupFull* GroupFull::default_instance_ = NULL;

GroupFull* GroupFull::New(::google::protobuf::Arena* arena) const {
  GroupFull* n = new GroupFull;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GroupFull::Swap(GroupFull* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GroupFull::InternalSwap(GroupFull* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GroupFull::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GroupFull_descriptor_;
  metadata.reflection = GroupFull_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GroupFull

// optional string id = 1;
void GroupFull::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& GroupFull::id() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.GroupFull.id)
}
 void GroupFull::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.GroupFull.id)
}
 void GroupFull::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.GroupFull.id)
}
 ::std::string* GroupFull::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:zproto.GroupFull.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GroupFull::release_id() {
  // @@protoc_insertion_point(field_release:zproto.GroupFull.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:zproto.GroupFull.id)
}

// optional int64 create_date = 2;
void GroupFull::clear_create_date() {
  create_date_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 GroupFull::create_date() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.create_date)
  return create_date_;
}
 void GroupFull::set_create_date(::google::protobuf::int64 value) {
  
  create_date_ = value;
  // @@protoc_insertion_point(field_set:zproto.GroupFull.create_date)
}

// optional string owner_uid = 3;
void GroupFull::clear_owner_uid() {
  owner_uid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& GroupFull::owner_uid() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.owner_uid)
  return owner_uid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_owner_uid(const ::std::string& value) {
  
  owner_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.GroupFull.owner_uid)
}
 void GroupFull::set_owner_uid(const char* value) {
  
  owner_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.GroupFull.owner_uid)
}
 void GroupFull::set_owner_uid(const char* value, size_t size) {
  
  owner_uid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.GroupFull.owner_uid)
}
 ::std::string* GroupFull::mutable_owner_uid() {
  
  // @@protoc_insertion_point(field_mutable:zproto.GroupFull.owner_uid)
  return owner_uid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GroupFull::release_owner_uid() {
  // @@protoc_insertion_point(field_release:zproto.GroupFull.owner_uid)
  
  return owner_uid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_allocated_owner_uid(::std::string* owner_uid) {
  if (owner_uid != NULL) {
    
  } else {
    
  }
  owner_uid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), owner_uid);
  // @@protoc_insertion_point(field_set_allocated:zproto.GroupFull.owner_uid)
}

// repeated .zproto.Member members = 4;
int GroupFull::members_size() const {
  return members_.size();
}
void GroupFull::clear_members() {
  members_.Clear();
}
const ::zproto::Member& GroupFull::members(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.members)
  return members_.Get(index);
}
::zproto::Member* GroupFull::mutable_members(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GroupFull.members)
  return members_.Mutable(index);
}
::zproto::Member* GroupFull::add_members() {
  // @@protoc_insertion_point(field_add:zproto.GroupFull.members)
  return members_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::Member >*
GroupFull::mutable_members() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GroupFull.members)
  return &members_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::Member >&
GroupFull::members() const {
  // @@protoc_insertion_point(field_list:zproto.GroupFull.members)
  return members_;
}

// optional string theme = 5;
void GroupFull::clear_theme() {
  theme_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& GroupFull::theme() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.theme)
  return theme_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_theme(const ::std::string& value) {
  
  theme_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.GroupFull.theme)
}
 void GroupFull::set_theme(const char* value) {
  
  theme_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.GroupFull.theme)
}
 void GroupFull::set_theme(const char* value, size_t size) {
  
  theme_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.GroupFull.theme)
}
 ::std::string* GroupFull::mutable_theme() {
  
  // @@protoc_insertion_point(field_mutable:zproto.GroupFull.theme)
  return theme_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GroupFull::release_theme() {
  // @@protoc_insertion_point(field_release:zproto.GroupFull.theme)
  
  return theme_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_allocated_theme(::std::string* theme) {
  if (theme != NULL) {
    
  } else {
    
  }
  theme_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), theme);
  // @@protoc_insertion_point(field_set_allocated:zproto.GroupFull.theme)
}

// optional string about = 6;
void GroupFull::clear_about() {
  about_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& GroupFull::about() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.about)
  return about_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_about(const ::std::string& value) {
  
  about_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.GroupFull.about)
}
 void GroupFull::set_about(const char* value) {
  
  about_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.GroupFull.about)
}
 void GroupFull::set_about(const char* value, size_t size) {
  
  about_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.GroupFull.about)
}
 ::std::string* GroupFull::mutable_about() {
  
  // @@protoc_insertion_point(field_mutable:zproto.GroupFull.about)
  return about_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GroupFull::release_about() {
  // @@protoc_insertion_point(field_release:zproto.GroupFull.about)
  
  return about_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_allocated_about(::std::string* about) {
  if (about != NULL) {
    
  } else {
    
  }
  about_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), about);
  // @@protoc_insertion_point(field_set_allocated:zproto.GroupFull.about)
}

// map<string, .zproto.RawArrayValue> ext = 7;
int GroupFull::ext_size() const {
  return ext_.size();
}
void GroupFull::clear_ext() {
  ext_.Clear();
}
 const ::google::protobuf::Map< ::std::string, ::zproto::RawArrayValue >&
GroupFull::ext() const {
  // @@protoc_insertion_point(field_map:zproto.GroupFull.ext)
  return ext_.GetMap();
}
 ::google::protobuf::Map< ::std::string, ::zproto::RawArrayValue >*
GroupFull::mutable_ext() {
  // @@protoc_insertion_point(field_mutable_map:zproto.GroupFull.ext)
  return ext_.MutableMap();
}

// optional bool is_async_members = 8;
void GroupFull::clear_is_async_members() {
  is_async_members_ = false;
}
 bool GroupFull::is_async_members() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.is_async_members)
  return is_async_members_;
}
 void GroupFull::set_is_async_members(bool value) {
  
  is_async_members_ = value;
  // @@protoc_insertion_point(field_set:zproto.GroupFull.is_async_members)
}

// optional bool is_shared_history = 9;
void GroupFull::clear_is_shared_history() {
  is_shared_history_ = false;
}
 bool GroupFull::is_shared_history() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.is_shared_history)
  return is_shared_history_;
}
 void GroupFull::set_is_shared_history(bool value) {
  
  is_shared_history_ = value;
  // @@protoc_insertion_point(field_set:zproto.GroupFull.is_shared_history)
}

// optional string short_name = 10;
void GroupFull::clear_short_name() {
  short_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& GroupFull::short_name() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.short_name)
  return short_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_short_name(const ::std::string& value) {
  
  short_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.GroupFull.short_name)
}
 void GroupFull::set_short_name(const char* value) {
  
  short_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.GroupFull.short_name)
}
 void GroupFull::set_short_name(const char* value, size_t size) {
  
  short_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.GroupFull.short_name)
}
 ::std::string* GroupFull::mutable_short_name() {
  
  // @@protoc_insertion_point(field_mutable:zproto.GroupFull.short_name)
  return short_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GroupFull::release_short_name() {
  // @@protoc_insertion_point(field_release:zproto.GroupFull.short_name)
  
  return short_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GroupFull::set_allocated_short_name(::std::string* short_name) {
  if (short_name != NULL) {
    
  } else {
    
  }
  short_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), short_name);
  // @@protoc_insertion_point(field_set_allocated:zproto.GroupFull.short_name)
}

// optional int64 permissions = 11;
void GroupFull::clear_permissions() {
  permissions_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 GroupFull::permissions() const {
  // @@protoc_insertion_point(field_get:zproto.GroupFull.permissions)
  return permissions_;
}
 void GroupFull::set_permissions(::google::protobuf::int64 value) {
  
  permissions_ = value;
  // @@protoc_insertion_point(field_set:zproto.GroupFull.permissions)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)
