// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sequence.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "sequence.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace zproto {

namespace {

const ::google::protobuf::Descriptor* GetStateReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetStateReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetDifferenceReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetDifferenceReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetDifferenceRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetDifferenceRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetReferencedEntititesReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetReferencedEntititesReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* GetReferencedEntititesRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GetReferencedEntititesRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* RawUpdateNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RawUpdateNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* EmptyUpdateNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  EmptyUpdateNotify_reflection_ = NULL;
const ::google::protobuf::Descriptor* SubscribeToOnlineReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SubscribeToOnlineReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* SubscribeFromOnlineReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SubscribeFromOnlineReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* SubscribeToGroupOnlineReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SubscribeToGroupOnlineReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* SubscribeFromGroupOnlineReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SubscribeFromGroupOnlineReq_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_sequence_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_sequence_2eproto() {
  protobuf_AddDesc_sequence_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "sequence.proto");
  GOOGLE_CHECK(file != NULL);
  GetStateReq_descriptor_ = file->message_type(0);
  static const int GetStateReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetStateReq, optimizations_),
  };
  GetStateReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetStateReq_descriptor_,
      GetStateReq::default_instance_,
      GetStateReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetStateReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetStateReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetStateReq, _is_default_instance_));
  GetDifferenceReq_descriptor_ = file->message_type(1);
  static const int GetDifferenceReq_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceReq, seq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceReq, state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceReq, optimizations_),
  };
  GetDifferenceReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetDifferenceReq_descriptor_,
      GetDifferenceReq::default_instance_,
      GetDifferenceReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetDifferenceReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceReq, _is_default_instance_));
  GetDifferenceRsp_descriptor_ = file->message_type(2);
  static const int GetDifferenceRsp_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, seq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, users_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, groups_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, updates_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, messages_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, need_more_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, users_refs_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, groups_refs_),
  };
  GetDifferenceRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetDifferenceRsp_descriptor_,
      GetDifferenceRsp::default_instance_,
      GetDifferenceRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetDifferenceRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetDifferenceRsp, _is_default_instance_));
  GetReferencedEntititesReq_descriptor_ = file->message_type(3);
  static const int GetReferencedEntititesReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetReferencedEntititesReq, users_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetReferencedEntititesReq, groups_),
  };
  GetReferencedEntititesReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetReferencedEntititesReq_descriptor_,
      GetReferencedEntititesReq::default_instance_,
      GetReferencedEntititesReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetReferencedEntititesReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetReferencedEntititesReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetReferencedEntititesReq, _is_default_instance_));
  GetReferencedEntititesRsp_descriptor_ = file->message_type(4);
  static const int GetReferencedEntititesRsp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetReferencedEntititesRsp, users_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetReferencedEntititesRsp, groups_),
  };
  GetReferencedEntititesRsp_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      GetReferencedEntititesRsp_descriptor_,
      GetReferencedEntititesRsp::default_instance_,
      GetReferencedEntititesRsp_offsets_,
      -1,
      -1,
      -1,
      sizeof(GetReferencedEntititesRsp),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetReferencedEntititesRsp, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GetReferencedEntititesRsp, _is_default_instance_));
  RawUpdateNotify_descriptor_ = file->message_type(5);
  static const int RawUpdateNotify_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawUpdateNotify, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawUpdateNotify, bytes_),
  };
  RawUpdateNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      RawUpdateNotify_descriptor_,
      RawUpdateNotify::default_instance_,
      RawUpdateNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(RawUpdateNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawUpdateNotify, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RawUpdateNotify, _is_default_instance_));
  EmptyUpdateNotify_descriptor_ = file->message_type(6);
  static const int EmptyUpdateNotify_offsets_[1] = {
  };
  EmptyUpdateNotify_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      EmptyUpdateNotify_descriptor_,
      EmptyUpdateNotify::default_instance_,
      EmptyUpdateNotify_offsets_,
      -1,
      -1,
      -1,
      sizeof(EmptyUpdateNotify),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmptyUpdateNotify, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EmptyUpdateNotify, _is_default_instance_));
  SubscribeToOnlineReq_descriptor_ = file->message_type(7);
  static const int SubscribeToOnlineReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeToOnlineReq, users_),
  };
  SubscribeToOnlineReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SubscribeToOnlineReq_descriptor_,
      SubscribeToOnlineReq::default_instance_,
      SubscribeToOnlineReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(SubscribeToOnlineReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeToOnlineReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeToOnlineReq, _is_default_instance_));
  SubscribeFromOnlineReq_descriptor_ = file->message_type(8);
  static const int SubscribeFromOnlineReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeFromOnlineReq, users_),
  };
  SubscribeFromOnlineReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SubscribeFromOnlineReq_descriptor_,
      SubscribeFromOnlineReq::default_instance_,
      SubscribeFromOnlineReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(SubscribeFromOnlineReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeFromOnlineReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeFromOnlineReq, _is_default_instance_));
  SubscribeToGroupOnlineReq_descriptor_ = file->message_type(9);
  static const int SubscribeToGroupOnlineReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeToGroupOnlineReq, groups_),
  };
  SubscribeToGroupOnlineReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SubscribeToGroupOnlineReq_descriptor_,
      SubscribeToGroupOnlineReq::default_instance_,
      SubscribeToGroupOnlineReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(SubscribeToGroupOnlineReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeToGroupOnlineReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeToGroupOnlineReq, _is_default_instance_));
  SubscribeFromGroupOnlineReq_descriptor_ = file->message_type(10);
  static const int SubscribeFromGroupOnlineReq_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeFromGroupOnlineReq, groups_),
  };
  SubscribeFromGroupOnlineReq_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SubscribeFromGroupOnlineReq_descriptor_,
      SubscribeFromGroupOnlineReq::default_instance_,
      SubscribeFromGroupOnlineReq_offsets_,
      -1,
      -1,
      -1,
      sizeof(SubscribeFromGroupOnlineReq),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeFromGroupOnlineReq, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SubscribeFromGroupOnlineReq, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_sequence_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetStateReq_descriptor_, &GetStateReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetDifferenceReq_descriptor_, &GetDifferenceReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetDifferenceRsp_descriptor_, &GetDifferenceRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetReferencedEntititesReq_descriptor_, &GetReferencedEntititesReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      GetReferencedEntititesRsp_descriptor_, &GetReferencedEntititesRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      RawUpdateNotify_descriptor_, &RawUpdateNotify::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      EmptyUpdateNotify_descriptor_, &EmptyUpdateNotify::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SubscribeToOnlineReq_descriptor_, &SubscribeToOnlineReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SubscribeFromOnlineReq_descriptor_, &SubscribeFromOnlineReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SubscribeToGroupOnlineReq_descriptor_, &SubscribeToGroupOnlineReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SubscribeFromGroupOnlineReq_descriptor_, &SubscribeFromGroupOnlineReq::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_sequence_2eproto() {
  delete GetStateReq::default_instance_;
  delete GetStateReq_reflection_;
  delete GetDifferenceReq::default_instance_;
  delete GetDifferenceReq_reflection_;
  delete GetDifferenceRsp::default_instance_;
  delete GetDifferenceRsp_reflection_;
  delete GetReferencedEntititesReq::default_instance_;
  delete GetReferencedEntititesReq_reflection_;
  delete GetReferencedEntititesRsp::default_instance_;
  delete GetReferencedEntititesRsp_reflection_;
  delete RawUpdateNotify::default_instance_;
  delete RawUpdateNotify_reflection_;
  delete EmptyUpdateNotify::default_instance_;
  delete EmptyUpdateNotify_reflection_;
  delete SubscribeToOnlineReq::default_instance_;
  delete SubscribeToOnlineReq_reflection_;
  delete SubscribeFromOnlineReq::default_instance_;
  delete SubscribeFromOnlineReq_reflection_;
  delete SubscribeToGroupOnlineReq::default_instance_;
  delete SubscribeToGroupOnlineReq_reflection_;
  delete SubscribeFromGroupOnlineReq::default_instance_;
  delete SubscribeFromGroupOnlineReq_reflection_;
}

void protobuf_AddDesc_sequence_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_sequence_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::zproto::protobuf_AddDesc_peers_2eproto();
  ::zproto::protobuf_AddDesc_users_2eproto();
  ::zproto::protobuf_AddDesc_group_5fbase_2eproto();
  ::zproto::protobuf_AddDesc_messaging_5fbase_2eproto();
  ::zproto::protobuf_AddDesc_sequence_5fbase_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016sequence.proto\022\006zproto\032\013peers.proto\032\013u"
    "sers.proto\032\020group_base.proto\032\024messaging_"
    "base.proto\032\023sequence_base.proto\"@\n\013GetSt"
    "ateReq\0221\n\roptimizations\030\001 \003(\0162\032.zproto.U"
    "pdateOptimization\"a\n\020GetDifferenceReq\022\013\n"
    "\003seq\030\001 \001(\005\022\r\n\005state\030\002 \001(\014\0221\n\roptimizatio"
    "ns\030\003 \003(\0162\032.zproto.UpdateOptimization\"\247\002\n"
    "\020GetDifferenceRsp\022\013\n\003seq\030\001 \001(\005\022\r\n\005state\030"
    "\002 \001(\014\022\033\n\005users\030\003 \003(\0132\014.zproto.User\022\035\n\006gr"
    "oups\030\004 \003(\0132\r.zproto.Group\022(\n\007updates\030\005 \003"
    "(\0132\027.zproto.UpdateContainer\022*\n\010messages\030"
    "\006 \003(\0132\030.zproto.MessageContainer\022\021\n\tneed_"
    "more\030\007 \001(\010\022\'\n\nusers_refs\030\010 \003(\0132\023.zproto."
    "UserOutPeer\022)\n\013groups_refs\030\t \003(\0132\024.zprot"
    "o.GroupOutPeer\"e\n\031GetReferencedEntitites"
    "Req\022\"\n\005users\030\001 \003(\0132\023.zproto.UserOutPeer\022"
    "$\n\006groups\030\002 \003(\0132\024.zproto.GroupOutPeer\"W\n"
    "\031GetReferencedEntititesRsp\022\033\n\005users\030\001 \003("
    "\0132\014.zproto.User\022\035\n\006groups\030\002 \003(\0132\r.zproto"
    ".Group\".\n\017RawUpdateNotify\022\014\n\004type\030\001 \001(\t\022"
    "\r\n\005bytes\030\002 \001(\014\"\023\n\021EmptyUpdateNotify\":\n\024S"
    "ubscribeToOnlineReq\022\"\n\005users\030\001 \003(\0132\023.zpr"
    "oto.UserOutPeer\"<\n\026SubscribeFromOnlineRe"
    "q\022\"\n\005users\030\001 \003(\0132\023.zproto.UserOutPeer\"A\n"
    "\031SubscribeToGroupOnlineReq\022$\n\006groups\030\001 \003"
    "(\0132\024.zproto.GroupOutPeer\"C\n\033SubscribeFro"
    "mGroupOnlineReq\022$\n\006groups\030\001 \003(\0132\024.zproto"
    ".GroupOutPeerB+\n\027com.zchat.engine.zproto"
    "B\016ZProtoSequenceH\002b\006proto3", 1146);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sequence.proto", &protobuf_RegisterTypes);
  GetStateReq::default_instance_ = new GetStateReq();
  GetDifferenceReq::default_instance_ = new GetDifferenceReq();
  GetDifferenceRsp::default_instance_ = new GetDifferenceRsp();
  GetReferencedEntititesReq::default_instance_ = new GetReferencedEntititesReq();
  GetReferencedEntititesRsp::default_instance_ = new GetReferencedEntititesRsp();
  RawUpdateNotify::default_instance_ = new RawUpdateNotify();
  EmptyUpdateNotify::default_instance_ = new EmptyUpdateNotify();
  SubscribeToOnlineReq::default_instance_ = new SubscribeToOnlineReq();
  SubscribeFromOnlineReq::default_instance_ = new SubscribeFromOnlineReq();
  SubscribeToGroupOnlineReq::default_instance_ = new SubscribeToGroupOnlineReq();
  SubscribeFromGroupOnlineReq::default_instance_ = new SubscribeFromGroupOnlineReq();
  GetStateReq::default_instance_->InitAsDefaultInstance();
  GetDifferenceReq::default_instance_->InitAsDefaultInstance();
  GetDifferenceRsp::default_instance_->InitAsDefaultInstance();
  GetReferencedEntititesReq::default_instance_->InitAsDefaultInstance();
  GetReferencedEntititesRsp::default_instance_->InitAsDefaultInstance();
  RawUpdateNotify::default_instance_->InitAsDefaultInstance();
  EmptyUpdateNotify::default_instance_->InitAsDefaultInstance();
  SubscribeToOnlineReq::default_instance_->InitAsDefaultInstance();
  SubscribeFromOnlineReq::default_instance_->InitAsDefaultInstance();
  SubscribeToGroupOnlineReq::default_instance_->InitAsDefaultInstance();
  SubscribeFromGroupOnlineReq::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_sequence_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_sequence_2eproto {
  StaticDescriptorInitializer_sequence_2eproto() {
    protobuf_AddDesc_sequence_2eproto();
  }
} static_descriptor_initializer_sequence_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetStateReq::kOptimizationsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetStateReq::GetStateReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GetStateReq)
}

void GetStateReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GetStateReq::GetStateReq(const GetStateReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GetStateReq)
}

void GetStateReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

GetStateReq::~GetStateReq() {
  // @@protoc_insertion_point(destructor:zproto.GetStateReq)
  SharedDtor();
}

void GetStateReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GetStateReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetStateReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetStateReq_descriptor_;
}

const GetStateReq& GetStateReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

GetStateReq* GetStateReq::default_instance_ = NULL;

GetStateReq* GetStateReq::New(::google::protobuf::Arena* arena) const {
  GetStateReq* n = new GetStateReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetStateReq::Swap(GetStateReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetStateReq::InternalSwap(GetStateReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GetStateReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetStateReq_descriptor_;
  metadata.reflection = GetStateReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetStateReq

// repeated .zproto.UpdateOptimization optimizations = 1;
int GetStateReq::optimizations_size() const {
  return optimizations_.size();
}
void GetStateReq::clear_optimizations() {
  optimizations_.Clear();
}
 ::zproto::UpdateOptimization GetStateReq::optimizations(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetStateReq.optimizations)
  return static_cast< ::zproto::UpdateOptimization >(optimizations_.Get(index));
}
 void GetStateReq::set_optimizations(int index, ::zproto::UpdateOptimization value) {
  optimizations_.Set(index, value);
  // @@protoc_insertion_point(field_set:zproto.GetStateReq.optimizations)
}
 void GetStateReq::add_optimizations(::zproto::UpdateOptimization value) {
  optimizations_.Add(value);
  // @@protoc_insertion_point(field_add:zproto.GetStateReq.optimizations)
}
 const ::google::protobuf::RepeatedField<int>&
GetStateReq::optimizations() const {
  // @@protoc_insertion_point(field_list:zproto.GetStateReq.optimizations)
  return optimizations_;
}
 ::google::protobuf::RepeatedField<int>*
GetStateReq::mutable_optimizations() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetStateReq.optimizations)
  return &optimizations_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetDifferenceReq::kSeqFieldNumber;
const int GetDifferenceReq::kStateFieldNumber;
const int GetDifferenceReq::kOptimizationsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetDifferenceReq::GetDifferenceReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GetDifferenceReq)
}

void GetDifferenceReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GetDifferenceReq::GetDifferenceReq(const GetDifferenceReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GetDifferenceReq)
}

void GetDifferenceReq::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  seq_ = 0;
  state_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GetDifferenceReq::~GetDifferenceReq() {
  // @@protoc_insertion_point(destructor:zproto.GetDifferenceReq)
  SharedDtor();
}

void GetDifferenceReq::SharedDtor() {
  state_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void GetDifferenceReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetDifferenceReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetDifferenceReq_descriptor_;
}

const GetDifferenceReq& GetDifferenceReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

GetDifferenceReq* GetDifferenceReq::default_instance_ = NULL;

GetDifferenceReq* GetDifferenceReq::New(::google::protobuf::Arena* arena) const {
  GetDifferenceReq* n = new GetDifferenceReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetDifferenceReq::Swap(GetDifferenceReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetDifferenceReq::InternalSwap(GetDifferenceReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GetDifferenceReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetDifferenceReq_descriptor_;
  metadata.reflection = GetDifferenceReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetDifferenceReq

// optional int32 seq = 1;
void GetDifferenceReq::clear_seq() {
  seq_ = 0;
}
 ::google::protobuf::int32 GetDifferenceReq::seq() const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceReq.seq)
  return seq_;
}
 void GetDifferenceReq::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:zproto.GetDifferenceReq.seq)
}

// optional bytes state = 2;
void GetDifferenceReq::clear_state() {
  state_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& GetDifferenceReq::state() const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceReq.state)
  return state_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetDifferenceReq::set_state(const ::std::string& value) {
  
  state_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.GetDifferenceReq.state)
}
 void GetDifferenceReq::set_state(const char* value) {
  
  state_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.GetDifferenceReq.state)
}
 void GetDifferenceReq::set_state(const void* value, size_t size) {
  
  state_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.GetDifferenceReq.state)
}
 ::std::string* GetDifferenceReq::mutable_state() {
  
  // @@protoc_insertion_point(field_mutable:zproto.GetDifferenceReq.state)
  return state_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GetDifferenceReq::release_state() {
  // @@protoc_insertion_point(field_release:zproto.GetDifferenceReq.state)
  
  return state_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetDifferenceReq::set_allocated_state(::std::string* state) {
  if (state != NULL) {
    
  } else {
    
  }
  state_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), state);
  // @@protoc_insertion_point(field_set_allocated:zproto.GetDifferenceReq.state)
}

// repeated .zproto.UpdateOptimization optimizations = 3;
int GetDifferenceReq::optimizations_size() const {
  return optimizations_.size();
}
void GetDifferenceReq::clear_optimizations() {
  optimizations_.Clear();
}
 ::zproto::UpdateOptimization GetDifferenceReq::optimizations(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceReq.optimizations)
  return static_cast< ::zproto::UpdateOptimization >(optimizations_.Get(index));
}
 void GetDifferenceReq::set_optimizations(int index, ::zproto::UpdateOptimization value) {
  optimizations_.Set(index, value);
  // @@protoc_insertion_point(field_set:zproto.GetDifferenceReq.optimizations)
}
 void GetDifferenceReq::add_optimizations(::zproto::UpdateOptimization value) {
  optimizations_.Add(value);
  // @@protoc_insertion_point(field_add:zproto.GetDifferenceReq.optimizations)
}
 const ::google::protobuf::RepeatedField<int>&
GetDifferenceReq::optimizations() const {
  // @@protoc_insertion_point(field_list:zproto.GetDifferenceReq.optimizations)
  return optimizations_;
}
 ::google::protobuf::RepeatedField<int>*
GetDifferenceReq::mutable_optimizations() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetDifferenceReq.optimizations)
  return &optimizations_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetDifferenceRsp::kSeqFieldNumber;
const int GetDifferenceRsp::kStateFieldNumber;
const int GetDifferenceRsp::kUsersFieldNumber;
const int GetDifferenceRsp::kGroupsFieldNumber;
const int GetDifferenceRsp::kUpdatesFieldNumber;
const int GetDifferenceRsp::kMessagesFieldNumber;
const int GetDifferenceRsp::kNeedMoreFieldNumber;
const int GetDifferenceRsp::kUsersRefsFieldNumber;
const int GetDifferenceRsp::kGroupsRefsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetDifferenceRsp::GetDifferenceRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GetDifferenceRsp)
}

void GetDifferenceRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GetDifferenceRsp::GetDifferenceRsp(const GetDifferenceRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GetDifferenceRsp)
}

void GetDifferenceRsp::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  seq_ = 0;
  state_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  need_more_ = false;
}

GetDifferenceRsp::~GetDifferenceRsp() {
  // @@protoc_insertion_point(destructor:zproto.GetDifferenceRsp)
  SharedDtor();
}

void GetDifferenceRsp::SharedDtor() {
  state_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void GetDifferenceRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetDifferenceRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetDifferenceRsp_descriptor_;
}

const GetDifferenceRsp& GetDifferenceRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

GetDifferenceRsp* GetDifferenceRsp::default_instance_ = NULL;

GetDifferenceRsp* GetDifferenceRsp::New(::google::protobuf::Arena* arena) const {
  GetDifferenceRsp* n = new GetDifferenceRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetDifferenceRsp::Swap(GetDifferenceRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetDifferenceRsp::InternalSwap(GetDifferenceRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GetDifferenceRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetDifferenceRsp_descriptor_;
  metadata.reflection = GetDifferenceRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetDifferenceRsp

// optional int32 seq = 1;
void GetDifferenceRsp::clear_seq() {
  seq_ = 0;
}
 ::google::protobuf::int32 GetDifferenceRsp::seq() const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.seq)
  return seq_;
}
 void GetDifferenceRsp::set_seq(::google::protobuf::int32 value) {
  
  seq_ = value;
  // @@protoc_insertion_point(field_set:zproto.GetDifferenceRsp.seq)
}

// optional bytes state = 2;
void GetDifferenceRsp::clear_state() {
  state_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& GetDifferenceRsp::state() const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.state)
  return state_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetDifferenceRsp::set_state(const ::std::string& value) {
  
  state_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.GetDifferenceRsp.state)
}
 void GetDifferenceRsp::set_state(const char* value) {
  
  state_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.GetDifferenceRsp.state)
}
 void GetDifferenceRsp::set_state(const void* value, size_t size) {
  
  state_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.GetDifferenceRsp.state)
}
 ::std::string* GetDifferenceRsp::mutable_state() {
  
  // @@protoc_insertion_point(field_mutable:zproto.GetDifferenceRsp.state)
  return state_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* GetDifferenceRsp::release_state() {
  // @@protoc_insertion_point(field_release:zproto.GetDifferenceRsp.state)
  
  return state_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void GetDifferenceRsp::set_allocated_state(::std::string* state) {
  if (state != NULL) {
    
  } else {
    
  }
  state_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), state);
  // @@protoc_insertion_point(field_set_allocated:zproto.GetDifferenceRsp.state)
}

// repeated .zproto.User users = 3;
int GetDifferenceRsp::users_size() const {
  return users_.size();
}
void GetDifferenceRsp::clear_users() {
  users_.Clear();
}
const ::zproto::User& GetDifferenceRsp::users(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.users)
  return users_.Get(index);
}
::zproto::User* GetDifferenceRsp::mutable_users(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetDifferenceRsp.users)
  return users_.Mutable(index);
}
::zproto::User* GetDifferenceRsp::add_users() {
  // @@protoc_insertion_point(field_add:zproto.GetDifferenceRsp.users)
  return users_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::User >*
GetDifferenceRsp::mutable_users() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetDifferenceRsp.users)
  return &users_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::User >&
GetDifferenceRsp::users() const {
  // @@protoc_insertion_point(field_list:zproto.GetDifferenceRsp.users)
  return users_;
}

// repeated .zproto.Group groups = 4;
int GetDifferenceRsp::groups_size() const {
  return groups_.size();
}
void GetDifferenceRsp::clear_groups() {
  groups_.Clear();
}
const ::zproto::Group& GetDifferenceRsp::groups(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.groups)
  return groups_.Get(index);
}
::zproto::Group* GetDifferenceRsp::mutable_groups(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetDifferenceRsp.groups)
  return groups_.Mutable(index);
}
::zproto::Group* GetDifferenceRsp::add_groups() {
  // @@protoc_insertion_point(field_add:zproto.GetDifferenceRsp.groups)
  return groups_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::Group >*
GetDifferenceRsp::mutable_groups() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetDifferenceRsp.groups)
  return &groups_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::Group >&
GetDifferenceRsp::groups() const {
  // @@protoc_insertion_point(field_list:zproto.GetDifferenceRsp.groups)
  return groups_;
}

// repeated .zproto.UpdateContainer updates = 5;
int GetDifferenceRsp::updates_size() const {
  return updates_.size();
}
void GetDifferenceRsp::clear_updates() {
  updates_.Clear();
}
const ::zproto::UpdateContainer& GetDifferenceRsp::updates(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.updates)
  return updates_.Get(index);
}
::zproto::UpdateContainer* GetDifferenceRsp::mutable_updates(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetDifferenceRsp.updates)
  return updates_.Mutable(index);
}
::zproto::UpdateContainer* GetDifferenceRsp::add_updates() {
  // @@protoc_insertion_point(field_add:zproto.GetDifferenceRsp.updates)
  return updates_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::UpdateContainer >*
GetDifferenceRsp::mutable_updates() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetDifferenceRsp.updates)
  return &updates_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::UpdateContainer >&
GetDifferenceRsp::updates() const {
  // @@protoc_insertion_point(field_list:zproto.GetDifferenceRsp.updates)
  return updates_;
}

// repeated .zproto.MessageContainer messages = 6;
int GetDifferenceRsp::messages_size() const {
  return messages_.size();
}
void GetDifferenceRsp::clear_messages() {
  messages_.Clear();
}
const ::zproto::MessageContainer& GetDifferenceRsp::messages(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.messages)
  return messages_.Get(index);
}
::zproto::MessageContainer* GetDifferenceRsp::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetDifferenceRsp.messages)
  return messages_.Mutable(index);
}
::zproto::MessageContainer* GetDifferenceRsp::add_messages() {
  // @@protoc_insertion_point(field_add:zproto.GetDifferenceRsp.messages)
  return messages_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::MessageContainer >*
GetDifferenceRsp::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetDifferenceRsp.messages)
  return &messages_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::MessageContainer >&
GetDifferenceRsp::messages() const {
  // @@protoc_insertion_point(field_list:zproto.GetDifferenceRsp.messages)
  return messages_;
}

// optional bool need_more = 7;
void GetDifferenceRsp::clear_need_more() {
  need_more_ = false;
}
 bool GetDifferenceRsp::need_more() const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.need_more)
  return need_more_;
}
 void GetDifferenceRsp::set_need_more(bool value) {
  
  need_more_ = value;
  // @@protoc_insertion_point(field_set:zproto.GetDifferenceRsp.need_more)
}

// repeated .zproto.UserOutPeer users_refs = 8;
int GetDifferenceRsp::users_refs_size() const {
  return users_refs_.size();
}
void GetDifferenceRsp::clear_users_refs() {
  users_refs_.Clear();
}
const ::zproto::UserOutPeer& GetDifferenceRsp::users_refs(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.users_refs)
  return users_refs_.Get(index);
}
::zproto::UserOutPeer* GetDifferenceRsp::mutable_users_refs(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetDifferenceRsp.users_refs)
  return users_refs_.Mutable(index);
}
::zproto::UserOutPeer* GetDifferenceRsp::add_users_refs() {
  // @@protoc_insertion_point(field_add:zproto.GetDifferenceRsp.users_refs)
  return users_refs_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::UserOutPeer >*
GetDifferenceRsp::mutable_users_refs() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetDifferenceRsp.users_refs)
  return &users_refs_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::UserOutPeer >&
GetDifferenceRsp::users_refs() const {
  // @@protoc_insertion_point(field_list:zproto.GetDifferenceRsp.users_refs)
  return users_refs_;
}

// repeated .zproto.GroupOutPeer groups_refs = 9;
int GetDifferenceRsp::groups_refs_size() const {
  return groups_refs_.size();
}
void GetDifferenceRsp::clear_groups_refs() {
  groups_refs_.Clear();
}
const ::zproto::GroupOutPeer& GetDifferenceRsp::groups_refs(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetDifferenceRsp.groups_refs)
  return groups_refs_.Get(index);
}
::zproto::GroupOutPeer* GetDifferenceRsp::mutable_groups_refs(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetDifferenceRsp.groups_refs)
  return groups_refs_.Mutable(index);
}
::zproto::GroupOutPeer* GetDifferenceRsp::add_groups_refs() {
  // @@protoc_insertion_point(field_add:zproto.GetDifferenceRsp.groups_refs)
  return groups_refs_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::GroupOutPeer >*
GetDifferenceRsp::mutable_groups_refs() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetDifferenceRsp.groups_refs)
  return &groups_refs_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::GroupOutPeer >&
GetDifferenceRsp::groups_refs() const {
  // @@protoc_insertion_point(field_list:zproto.GetDifferenceRsp.groups_refs)
  return groups_refs_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetReferencedEntititesReq::kUsersFieldNumber;
const int GetReferencedEntititesReq::kGroupsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetReferencedEntititesReq::GetReferencedEntititesReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GetReferencedEntititesReq)
}

void GetReferencedEntititesReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GetReferencedEntititesReq::GetReferencedEntititesReq(const GetReferencedEntititesReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GetReferencedEntititesReq)
}

void GetReferencedEntititesReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

GetReferencedEntititesReq::~GetReferencedEntititesReq() {
  // @@protoc_insertion_point(destructor:zproto.GetReferencedEntititesReq)
  SharedDtor();
}

void GetReferencedEntititesReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GetReferencedEntititesReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetReferencedEntititesReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetReferencedEntititesReq_descriptor_;
}

const GetReferencedEntititesReq& GetReferencedEntititesReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

GetReferencedEntititesReq* GetReferencedEntititesReq::default_instance_ = NULL;

GetReferencedEntititesReq* GetReferencedEntititesReq::New(::google::protobuf::Arena* arena) const {
  GetReferencedEntititesReq* n = new GetReferencedEntititesReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetReferencedEntititesReq::Swap(GetReferencedEntititesReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetReferencedEntititesReq::InternalSwap(GetReferencedEntititesReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GetReferencedEntititesReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetReferencedEntititesReq_descriptor_;
  metadata.reflection = GetReferencedEntititesReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetReferencedEntititesReq

// repeated .zproto.UserOutPeer users = 1;
int GetReferencedEntititesReq::users_size() const {
  return users_.size();
}
void GetReferencedEntititesReq::clear_users() {
  users_.Clear();
}
const ::zproto::UserOutPeer& GetReferencedEntititesReq::users(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetReferencedEntititesReq.users)
  return users_.Get(index);
}
::zproto::UserOutPeer* GetReferencedEntititesReq::mutable_users(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetReferencedEntititesReq.users)
  return users_.Mutable(index);
}
::zproto::UserOutPeer* GetReferencedEntititesReq::add_users() {
  // @@protoc_insertion_point(field_add:zproto.GetReferencedEntititesReq.users)
  return users_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::UserOutPeer >*
GetReferencedEntititesReq::mutable_users() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetReferencedEntititesReq.users)
  return &users_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::UserOutPeer >&
GetReferencedEntititesReq::users() const {
  // @@protoc_insertion_point(field_list:zproto.GetReferencedEntititesReq.users)
  return users_;
}

// repeated .zproto.GroupOutPeer groups = 2;
int GetReferencedEntititesReq::groups_size() const {
  return groups_.size();
}
void GetReferencedEntititesReq::clear_groups() {
  groups_.Clear();
}
const ::zproto::GroupOutPeer& GetReferencedEntititesReq::groups(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetReferencedEntititesReq.groups)
  return groups_.Get(index);
}
::zproto::GroupOutPeer* GetReferencedEntititesReq::mutable_groups(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetReferencedEntititesReq.groups)
  return groups_.Mutable(index);
}
::zproto::GroupOutPeer* GetReferencedEntititesReq::add_groups() {
  // @@protoc_insertion_point(field_add:zproto.GetReferencedEntititesReq.groups)
  return groups_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::GroupOutPeer >*
GetReferencedEntititesReq::mutable_groups() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetReferencedEntititesReq.groups)
  return &groups_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::GroupOutPeer >&
GetReferencedEntititesReq::groups() const {
  // @@protoc_insertion_point(field_list:zproto.GetReferencedEntititesReq.groups)
  return groups_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetReferencedEntititesRsp::kUsersFieldNumber;
const int GetReferencedEntititesRsp::kGroupsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetReferencedEntititesRsp::GetReferencedEntititesRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.GetReferencedEntititesRsp)
}

void GetReferencedEntititesRsp::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

GetReferencedEntititesRsp::GetReferencedEntititesRsp(const GetReferencedEntititesRsp& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.GetReferencedEntititesRsp)
}

void GetReferencedEntititesRsp::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

GetReferencedEntititesRsp::~GetReferencedEntititesRsp() {
  // @@protoc_insertion_point(destructor:zproto.GetReferencedEntititesRsp)
  SharedDtor();
}

void GetReferencedEntititesRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GetReferencedEntititesRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetReferencedEntititesRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GetReferencedEntititesRsp_descriptor_;
}

const GetReferencedEntititesRsp& GetReferencedEntititesRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

GetReferencedEntititesRsp* GetReferencedEntititesRsp::default_instance_ = NULL;

GetReferencedEntititesRsp* GetReferencedEntititesRsp::New(::google::protobuf::Arena* arena) const {
  GetReferencedEntititesRsp* n = new GetReferencedEntititesRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetReferencedEntititesRsp::Swap(GetReferencedEntititesRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetReferencedEntititesRsp::InternalSwap(GetReferencedEntititesRsp* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata GetReferencedEntititesRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GetReferencedEntititesRsp_descriptor_;
  metadata.reflection = GetReferencedEntititesRsp_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GetReferencedEntititesRsp

// repeated .zproto.User users = 1;
int GetReferencedEntititesRsp::users_size() const {
  return users_.size();
}
void GetReferencedEntititesRsp::clear_users() {
  users_.Clear();
}
const ::zproto::User& GetReferencedEntititesRsp::users(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetReferencedEntititesRsp.users)
  return users_.Get(index);
}
::zproto::User* GetReferencedEntititesRsp::mutable_users(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetReferencedEntititesRsp.users)
  return users_.Mutable(index);
}
::zproto::User* GetReferencedEntititesRsp::add_users() {
  // @@protoc_insertion_point(field_add:zproto.GetReferencedEntititesRsp.users)
  return users_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::User >*
GetReferencedEntititesRsp::mutable_users() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetReferencedEntititesRsp.users)
  return &users_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::User >&
GetReferencedEntititesRsp::users() const {
  // @@protoc_insertion_point(field_list:zproto.GetReferencedEntititesRsp.users)
  return users_;
}

// repeated .zproto.Group groups = 2;
int GetReferencedEntititesRsp::groups_size() const {
  return groups_.size();
}
void GetReferencedEntititesRsp::clear_groups() {
  groups_.Clear();
}
const ::zproto::Group& GetReferencedEntititesRsp::groups(int index) const {
  // @@protoc_insertion_point(field_get:zproto.GetReferencedEntititesRsp.groups)
  return groups_.Get(index);
}
::zproto::Group* GetReferencedEntititesRsp::mutable_groups(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.GetReferencedEntititesRsp.groups)
  return groups_.Mutable(index);
}
::zproto::Group* GetReferencedEntititesRsp::add_groups() {
  // @@protoc_insertion_point(field_add:zproto.GetReferencedEntititesRsp.groups)
  return groups_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::Group >*
GetReferencedEntititesRsp::mutable_groups() {
  // @@protoc_insertion_point(field_mutable_list:zproto.GetReferencedEntititesRsp.groups)
  return &groups_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::Group >&
GetReferencedEntititesRsp::groups() const {
  // @@protoc_insertion_point(field_list:zproto.GetReferencedEntititesRsp.groups)
  return groups_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RawUpdateNotify::kTypeFieldNumber;
const int RawUpdateNotify::kBytesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RawUpdateNotify::RawUpdateNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.RawUpdateNotify)
}

void RawUpdateNotify::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

RawUpdateNotify::RawUpdateNotify(const RawUpdateNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.RawUpdateNotify)
}

void RawUpdateNotify::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

RawUpdateNotify::~RawUpdateNotify() {
  // @@protoc_insertion_point(destructor:zproto.RawUpdateNotify)
  SharedDtor();
}

void RawUpdateNotify::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bytes_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void RawUpdateNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RawUpdateNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RawUpdateNotify_descriptor_;
}

const RawUpdateNotify& RawUpdateNotify::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

RawUpdateNotify* RawUpdateNotify::default_instance_ = NULL;

RawUpdateNotify* RawUpdateNotify::New(::google::protobuf::Arena* arena) const {
  RawUpdateNotify* n = new RawUpdateNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RawUpdateNotify::Swap(RawUpdateNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RawUpdateNotify::InternalSwap(RawUpdateNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata RawUpdateNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RawUpdateNotify_descriptor_;
  metadata.reflection = RawUpdateNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RawUpdateNotify

// optional string type = 1;
void RawUpdateNotify::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& RawUpdateNotify::type() const {
  // @@protoc_insertion_point(field_get:zproto.RawUpdateNotify.type)
  return type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RawUpdateNotify::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.RawUpdateNotify.type)
}
 void RawUpdateNotify::set_type(const char* value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.RawUpdateNotify.type)
}
 void RawUpdateNotify::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.RawUpdateNotify.type)
}
 ::std::string* RawUpdateNotify::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:zproto.RawUpdateNotify.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RawUpdateNotify::release_type() {
  // @@protoc_insertion_point(field_release:zproto.RawUpdateNotify.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RawUpdateNotify::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:zproto.RawUpdateNotify.type)
}

// optional bytes bytes = 2;
void RawUpdateNotify::clear_bytes() {
  bytes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& RawUpdateNotify::bytes() const {
  // @@protoc_insertion_point(field_get:zproto.RawUpdateNotify.bytes)
  return bytes_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RawUpdateNotify::set_bytes(const ::std::string& value) {
  
  bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.RawUpdateNotify.bytes)
}
 void RawUpdateNotify::set_bytes(const char* value) {
  
  bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.RawUpdateNotify.bytes)
}
 void RawUpdateNotify::set_bytes(const void* value, size_t size) {
  
  bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.RawUpdateNotify.bytes)
}
 ::std::string* RawUpdateNotify::mutable_bytes() {
  
  // @@protoc_insertion_point(field_mutable:zproto.RawUpdateNotify.bytes)
  return bytes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* RawUpdateNotify::release_bytes() {
  // @@protoc_insertion_point(field_release:zproto.RawUpdateNotify.bytes)
  
  return bytes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void RawUpdateNotify::set_allocated_bytes(::std::string* bytes) {
  if (bytes != NULL) {
    
  } else {
    
  }
  bytes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bytes);
  // @@protoc_insertion_point(field_set_allocated:zproto.RawUpdateNotify.bytes)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EmptyUpdateNotify::EmptyUpdateNotify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.EmptyUpdateNotify)
}

void EmptyUpdateNotify::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

EmptyUpdateNotify::EmptyUpdateNotify(const EmptyUpdateNotify& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.EmptyUpdateNotify)
}

void EmptyUpdateNotify::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

EmptyUpdateNotify::~EmptyUpdateNotify() {
  // @@protoc_insertion_point(destructor:zproto.EmptyUpdateNotify)
  SharedDtor();
}

void EmptyUpdateNotify::SharedDtor() {
  if (this != default_instance_) {
  }
}

void EmptyUpdateNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EmptyUpdateNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EmptyUpdateNotify_descriptor_;
}

const EmptyUpdateNotify& EmptyUpdateNotify::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

EmptyUpdateNotify* EmptyUpdateNotify::default_instance_ = NULL;

EmptyUpdateNotify* EmptyUpdateNotify::New(::google::protobuf::Arena* arena) const {
  EmptyUpdateNotify* n = new EmptyUpdateNotify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EmptyUpdateNotify::Swap(EmptyUpdateNotify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EmptyUpdateNotify::InternalSwap(EmptyUpdateNotify* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata EmptyUpdateNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = EmptyUpdateNotify_descriptor_;
  metadata.reflection = EmptyUpdateNotify_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EmptyUpdateNotify

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SubscribeToOnlineReq::kUsersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SubscribeToOnlineReq::SubscribeToOnlineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SubscribeToOnlineReq)
}

void SubscribeToOnlineReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SubscribeToOnlineReq::SubscribeToOnlineReq(const SubscribeToOnlineReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SubscribeToOnlineReq)
}

void SubscribeToOnlineReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

SubscribeToOnlineReq::~SubscribeToOnlineReq() {
  // @@protoc_insertion_point(destructor:zproto.SubscribeToOnlineReq)
  SharedDtor();
}

void SubscribeToOnlineReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SubscribeToOnlineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SubscribeToOnlineReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SubscribeToOnlineReq_descriptor_;
}

const SubscribeToOnlineReq& SubscribeToOnlineReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

SubscribeToOnlineReq* SubscribeToOnlineReq::default_instance_ = NULL;

SubscribeToOnlineReq* SubscribeToOnlineReq::New(::google::protobuf::Arena* arena) const {
  SubscribeToOnlineReq* n = new SubscribeToOnlineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SubscribeToOnlineReq::Swap(SubscribeToOnlineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SubscribeToOnlineReq::InternalSwap(SubscribeToOnlineReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SubscribeToOnlineReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SubscribeToOnlineReq_descriptor_;
  metadata.reflection = SubscribeToOnlineReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SubscribeToOnlineReq

// repeated .zproto.UserOutPeer users = 1;
int SubscribeToOnlineReq::users_size() const {
  return users_.size();
}
void SubscribeToOnlineReq::clear_users() {
  users_.Clear();
}
const ::zproto::UserOutPeer& SubscribeToOnlineReq::users(int index) const {
  // @@protoc_insertion_point(field_get:zproto.SubscribeToOnlineReq.users)
  return users_.Get(index);
}
::zproto::UserOutPeer* SubscribeToOnlineReq::mutable_users(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.SubscribeToOnlineReq.users)
  return users_.Mutable(index);
}
::zproto::UserOutPeer* SubscribeToOnlineReq::add_users() {
  // @@protoc_insertion_point(field_add:zproto.SubscribeToOnlineReq.users)
  return users_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::UserOutPeer >*
SubscribeToOnlineReq::mutable_users() {
  // @@protoc_insertion_point(field_mutable_list:zproto.SubscribeToOnlineReq.users)
  return &users_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::UserOutPeer >&
SubscribeToOnlineReq::users() const {
  // @@protoc_insertion_point(field_list:zproto.SubscribeToOnlineReq.users)
  return users_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SubscribeFromOnlineReq::kUsersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SubscribeFromOnlineReq::SubscribeFromOnlineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SubscribeFromOnlineReq)
}

void SubscribeFromOnlineReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SubscribeFromOnlineReq::SubscribeFromOnlineReq(const SubscribeFromOnlineReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SubscribeFromOnlineReq)
}

void SubscribeFromOnlineReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

SubscribeFromOnlineReq::~SubscribeFromOnlineReq() {
  // @@protoc_insertion_point(destructor:zproto.SubscribeFromOnlineReq)
  SharedDtor();
}

void SubscribeFromOnlineReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SubscribeFromOnlineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SubscribeFromOnlineReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SubscribeFromOnlineReq_descriptor_;
}

const SubscribeFromOnlineReq& SubscribeFromOnlineReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

SubscribeFromOnlineReq* SubscribeFromOnlineReq::default_instance_ = NULL;

SubscribeFromOnlineReq* SubscribeFromOnlineReq::New(::google::protobuf::Arena* arena) const {
  SubscribeFromOnlineReq* n = new SubscribeFromOnlineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SubscribeFromOnlineReq::Swap(SubscribeFromOnlineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SubscribeFromOnlineReq::InternalSwap(SubscribeFromOnlineReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SubscribeFromOnlineReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SubscribeFromOnlineReq_descriptor_;
  metadata.reflection = SubscribeFromOnlineReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SubscribeFromOnlineReq

// repeated .zproto.UserOutPeer users = 1;
int SubscribeFromOnlineReq::users_size() const {
  return users_.size();
}
void SubscribeFromOnlineReq::clear_users() {
  users_.Clear();
}
const ::zproto::UserOutPeer& SubscribeFromOnlineReq::users(int index) const {
  // @@protoc_insertion_point(field_get:zproto.SubscribeFromOnlineReq.users)
  return users_.Get(index);
}
::zproto::UserOutPeer* SubscribeFromOnlineReq::mutable_users(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.SubscribeFromOnlineReq.users)
  return users_.Mutable(index);
}
::zproto::UserOutPeer* SubscribeFromOnlineReq::add_users() {
  // @@protoc_insertion_point(field_add:zproto.SubscribeFromOnlineReq.users)
  return users_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::UserOutPeer >*
SubscribeFromOnlineReq::mutable_users() {
  // @@protoc_insertion_point(field_mutable_list:zproto.SubscribeFromOnlineReq.users)
  return &users_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::UserOutPeer >&
SubscribeFromOnlineReq::users() const {
  // @@protoc_insertion_point(field_list:zproto.SubscribeFromOnlineReq.users)
  return users_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SubscribeToGroupOnlineReq::kGroupsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SubscribeToGroupOnlineReq::SubscribeToGroupOnlineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SubscribeToGroupOnlineReq)
}

void SubscribeToGroupOnlineReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SubscribeToGroupOnlineReq::SubscribeToGroupOnlineReq(const SubscribeToGroupOnlineReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SubscribeToGroupOnlineReq)
}

void SubscribeToGroupOnlineReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

SubscribeToGroupOnlineReq::~SubscribeToGroupOnlineReq() {
  // @@protoc_insertion_point(destructor:zproto.SubscribeToGroupOnlineReq)
  SharedDtor();
}

void SubscribeToGroupOnlineReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SubscribeToGroupOnlineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SubscribeToGroupOnlineReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SubscribeToGroupOnlineReq_descriptor_;
}

const SubscribeToGroupOnlineReq& SubscribeToGroupOnlineReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

SubscribeToGroupOnlineReq* SubscribeToGroupOnlineReq::default_instance_ = NULL;

SubscribeToGroupOnlineReq* SubscribeToGroupOnlineReq::New(::google::protobuf::Arena* arena) const {
  SubscribeToGroupOnlineReq* n = new SubscribeToGroupOnlineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SubscribeToGroupOnlineReq::Swap(SubscribeToGroupOnlineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SubscribeToGroupOnlineReq::InternalSwap(SubscribeToGroupOnlineReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SubscribeToGroupOnlineReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SubscribeToGroupOnlineReq_descriptor_;
  metadata.reflection = SubscribeToGroupOnlineReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SubscribeToGroupOnlineReq

// repeated .zproto.GroupOutPeer groups = 1;
int SubscribeToGroupOnlineReq::groups_size() const {
  return groups_.size();
}
void SubscribeToGroupOnlineReq::clear_groups() {
  groups_.Clear();
}
const ::zproto::GroupOutPeer& SubscribeToGroupOnlineReq::groups(int index) const {
  // @@protoc_insertion_point(field_get:zproto.SubscribeToGroupOnlineReq.groups)
  return groups_.Get(index);
}
::zproto::GroupOutPeer* SubscribeToGroupOnlineReq::mutable_groups(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.SubscribeToGroupOnlineReq.groups)
  return groups_.Mutable(index);
}
::zproto::GroupOutPeer* SubscribeToGroupOnlineReq::add_groups() {
  // @@protoc_insertion_point(field_add:zproto.SubscribeToGroupOnlineReq.groups)
  return groups_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::GroupOutPeer >*
SubscribeToGroupOnlineReq::mutable_groups() {
  // @@protoc_insertion_point(field_mutable_list:zproto.SubscribeToGroupOnlineReq.groups)
  return &groups_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::GroupOutPeer >&
SubscribeToGroupOnlineReq::groups() const {
  // @@protoc_insertion_point(field_list:zproto.SubscribeToGroupOnlineReq.groups)
  return groups_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SubscribeFromGroupOnlineReq::kGroupsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SubscribeFromGroupOnlineReq::SubscribeFromGroupOnlineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.SubscribeFromGroupOnlineReq)
}

void SubscribeFromGroupOnlineReq::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

SubscribeFromGroupOnlineReq::SubscribeFromGroupOnlineReq(const SubscribeFromGroupOnlineReq& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:zproto.SubscribeFromGroupOnlineReq)
}

void SubscribeFromGroupOnlineReq::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

SubscribeFromGroupOnlineReq::~SubscribeFromGroupOnlineReq() {
  // @@protoc_insertion_point(destructor:zproto.SubscribeFromGroupOnlineReq)
  SharedDtor();
}

void SubscribeFromGroupOnlineReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SubscribeFromGroupOnlineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SubscribeFromGroupOnlineReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SubscribeFromGroupOnlineReq_descriptor_;
}

const SubscribeFromGroupOnlineReq& SubscribeFromGroupOnlineReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_sequence_2eproto();
  return *default_instance_;
}

SubscribeFromGroupOnlineReq* SubscribeFromGroupOnlineReq::default_instance_ = NULL;

SubscribeFromGroupOnlineReq* SubscribeFromGroupOnlineReq::New(::google::protobuf::Arena* arena) const {
  SubscribeFromGroupOnlineReq* n = new SubscribeFromGroupOnlineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SubscribeFromGroupOnlineReq::Swap(SubscribeFromGroupOnlineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SubscribeFromGroupOnlineReq::InternalSwap(SubscribeFromGroupOnlineReq* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata SubscribeFromGroupOnlineReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SubscribeFromGroupOnlineReq_descriptor_;
  metadata.reflection = SubscribeFromGroupOnlineReq_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SubscribeFromGroupOnlineReq

// repeated .zproto.GroupOutPeer groups = 1;
int SubscribeFromGroupOnlineReq::groups_size() const {
  return groups_.size();
}
void SubscribeFromGroupOnlineReq::clear_groups() {
  groups_.Clear();
}
const ::zproto::GroupOutPeer& SubscribeFromGroupOnlineReq::groups(int index) const {
  // @@protoc_insertion_point(field_get:zproto.SubscribeFromGroupOnlineReq.groups)
  return groups_.Get(index);
}
::zproto::GroupOutPeer* SubscribeFromGroupOnlineReq::mutable_groups(int index) {
  // @@protoc_insertion_point(field_mutable:zproto.SubscribeFromGroupOnlineReq.groups)
  return groups_.Mutable(index);
}
::zproto::GroupOutPeer* SubscribeFromGroupOnlineReq::add_groups() {
  // @@protoc_insertion_point(field_add:zproto.SubscribeFromGroupOnlineReq.groups)
  return groups_.Add();
}
::google::protobuf::RepeatedPtrField< ::zproto::GroupOutPeer >*
SubscribeFromGroupOnlineReq::mutable_groups() {
  // @@protoc_insertion_point(field_mutable_list:zproto.SubscribeFromGroupOnlineReq.groups)
  return &groups_;
}
const ::google::protobuf::RepeatedPtrField< ::zproto::GroupOutPeer >&
SubscribeFromGroupOnlineReq::groups() const {
  // @@protoc_insertion_point(field_list:zproto.SubscribeFromGroupOnlineReq.groups)
  return groups_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)
